name: Delete Workflows
run-name: ${{ github.actor }} is deleting workflows 🚀
jobs:
    Delete-Workflows:
        runs-on: ubuntu-latest
        steps:
            - uses: christosgalano/delete-workflow-runs@v1.0.0
              with:
                owner: ${{ inputs.repository_owner }}
                repo: ${{ inputs.repository_name }}
                token: ${{ secrets.workflow_PAT }}
                workflow: ${{ inputs.workflow_name }}